#!/usr/bin/env python3

import argparse

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.ticker as tick
import h5py
import mtd


fontsmall, fontnormal, fontlarge = 18, 24, 28
offblack = '#262626'

plt.rcdefaults()
plt.rcParams.update({
    'font.family': 'sans-serif',
    'font.sans-serif': ['Lato'],
    'mathtext.fontset': 'custom',
    'mathtext.default': 'it',
    'mathtext.rm': 'sans',
    'mathtext.it': 'sans:italic:medium',
    'mathtext.cal': 'sans',
    'font.size': fontnormal,
    'legend.fontsize': fontnormal,
    'axes.labelsize': fontnormal,
    'axes.titlesize': fontlarge,
    'xtick.labelsize': fontsmall,
    'ytick.labelsize': fontsmall,
    'font.weight': 400,
    'axes.labelweight': 400,
    'axes.titleweight': 400,
    'lines.linewidth': 1.5,
    'lines.markeredgewidth': 0,
    'patch.linewidth': 1.5,
    'axes.linewidth': 1,
    'xtick.major.width': 1,
    'ytick.major.width': 1,
    'xtick.minor.width': 1,
    'ytick.minor.width': 1,
    'xtick.major.size': 5,
    'ytick.major.size': 5,
    'xtick.minor.size': 3,
    'ytick.minor.size': 3,
    'xtick.major.pad': 8,
    'ytick.major.pad': 8,
    'text.color': offblack,
    'axes.edgecolor': offblack,
    'axes.labelcolor': offblack,
    'xtick.color': offblack,
    'ytick.color': offblack,
    'legend.numpoints': 1,
    'legend.scatterpoints': 1,
    'legend.frameon': False,
    'image.interpolation': 'none',
    'pdf.fonttype': 42
})


plot_functions = {}


def plot(f):
    def wrapper(*args, **kwargs):
        print(f.__name__)
        f(*args, **kwargs)
        plt.savefig('{}.pdf'.format(f.__name__))
        plt.close()

    plot_functions[f.__name__] = wrapper

    return wrapper


def finish(despine=True, remove_ticks=False, pad=0.1, h_pad=None, w_pad=None):
    fig = plt.gcf()

    for ax in fig.axes:
        if despine:
            for spine in 'top', 'right':
                ax.spines[spine].set_visible(False)

        if remove_ticks:
            for ax_name in 'xaxis', 'yaxis':
                getattr(ax, ax_name).set_ticks_position('none')
        else:
            ax.xaxis.set_ticks_position('bottom')
            ax.yaxis.set_ticks_position('left')

    fig.tight_layout(pad=pad, h_pad=h_pad, w_pad=w_pad)


def set_loc(ax, xy=None, nbins=5, steps=[1, 2, 3, 4, 10],
            prune=None, minor=0):
    if xy == 'x':
        axes = ax.xaxis,
    elif xy == 'y':
        axes = ax.yaxis,
    else:
        axes = ax.xaxis, ax.yaxis

    for axis in axes:
        axis.set_major_locator(
            tick.MaxNLocator(nbins=nbins, steps=steps, prune=prune)
        )
        if minor:
            axis.set_minor_locator(tick.AutoMinorLocator(minor))


@plot
def posterior(design, calibration, **kwargs):
    with h5py.File(design, 'r') as f:
        labels = list(f['labels'])
        etas_hrg_index = 4
        indices = np.arange(len(labels)) != etas_hrg_index
        del labels[etas_hrg_index]
        ranges = np.array(f['range'])[indices]

    with h5py.File(calibration, 'r') as f:
        chain = np.array(f['chain']).T[indices]

    nxy = chain.shape[0]
    assert nxy == len(labels)

    normal_cmap, highlight_cmap = plt.cm.Blues, plt.cm.Oranges

    fig, axes = plt.subplots(
        nrows=nxy, ncols=nxy,
        sharex='col', sharey='row',
        figsize=(21, 21)
    )

    for n, (ax, c, lim) in enumerate(zip(axes.diagonal(), chain, ranges)):
        cmap = highlight_cmap if n in [1, 6, 7] else normal_cmap
        line_color = cmap(.8)
        fill_color = cmap(.5, alpha=.1)

        # override range for norm
        if n == 0:
            lim = 100, 150

        counts, edges = np.histogram(c, bins=100, range=lim)
        x = (edges[1:] + edges[:-1]) / 2
        y = .84 * (lim[1] - lim[0]) * counts / counts.max() + lim[0]
        ax.plot(x, y, lw=2, color=line_color)
        ax.fill_between(x, lim[0], y, color=fill_color, zorder=-10)

        if n in [0, 1, 3, 6, 7]:
            mode = x[y.argmax()]
            fmt_str = '{:#.2g}' if n == 1 else '{:#.3g}'
            ax.text(mode, lim[1], fmt_str.format(mode),
                    ha='left' if mode < 0.4*sum(lim) else 'center', va='top')

        ax.set_xlim(lim)
        ax.set_ylim(lim)
        set_loc(ax, nbins=4, minor=2)

    for ny, nx in zip(*np.tril_indices_from(axes, k=-1)):
        H, xedges, yedges = np.histogram2d(
            chain[nx], chain[ny], bins=100, range=(ranges[nx], ranges[ny])
        )
        H[H == 0] = None
        cmap = highlight_cmap if (ny, nx) == (5, 4) else normal_cmap
        axes[ny][nx].pcolorfast(xedges, yedges, H.T, cmap=cmap)

        axes[nx][ny].set_axis_off()

    for n, label in enumerate(labels):
        axes[-1][n].set_xlabel(label)
        axes[n][0].set_ylabel(label)

    finish()


def _posterior_single(design, calibration, n):
    with h5py.File(design, 'r') as f:
        label = f['labels'][n]
        lim = f['range'][n]

    with h5py.File(calibration, 'r') as f:
        chain = f['chain'][:, n]

    fig = plt.figure(figsize=(7, 5))
    ax = fig.gca()

    counts, edges = np.histogram(chain, bins=100, range=lim)
    x = (edges[1:] + edges[:-1]) / 2
    y = counts
    ax.plot(x, y, lw=2, color=plt.cm.Blues(0.8))
    ax.fill_between(x, y, color=plt.cm.Blues(0.15), zorder=-10)

    mode = x[y.argmax()]
    fmt_str = '{:#.2g}' if n == 1 else '{:#.3g}'
    ax.text(mode, y.max() + .02*y.ptp(), fmt_str.format(mode),
            fontsize=22, ha='center', va='bottom')

    ax.set_xlim(lim)
    ax.set_xlabel(label)
    set_loc(ax, 'x', nbins=4, minor=2, steps=[1, 2, 3, 4, 5, 10])

    ax.spines['left'].set_visible(False)
    ax.set_yticks([])

    finish()


@plot
def posterior_p(design, calibration, **kwargs):
    _posterior_single(design, calibration, 1)


@plot
def posterior_bulk(design, calibration, **kwargs):
    _posterior_single(design, calibration, 7)


@plot
def posterior_tswitch(design, calibration, **kwargs):
    _posterior_single(design, calibration, 8)


@plot
def posterior_shear(design, calibration, **kwargs):
    fig = plt.figure(figsize=(8, 8))
    ratio = 5
    gs = plt.GridSpec(ratio + 1, ratio + 1)

    ax_j = fig.add_subplot(gs[1:, :-1])
    ax_x = fig.add_subplot(gs[0, :-1], sharex=ax_j)
    ax_y = fig.add_subplot(gs[1:, -1], sharey=ax_j)

    i, j = 5, 6

    with h5py.File(design, 'r') as f:
        xlabel = f['labels'][i]
        ylabel = f['labels'][j]
        xlim = f['range'][i, :]
        ylim = f['range'][j, :]

    with h5py.File(calibration, 'r') as f:
        x = f['chain'][:, i]
        y = f['chain'][:, j]

    H, xedges, yedges = np.histogram2d(x, y, bins=100, range=(xlim, ylim))
    H[H == 0] = None
    ax_j.pcolorfast(xedges, yedges, H.T, cmap=plt.cm.Blues)

    for chain, lim, ax in (x, xlim, ax_x), (y, ylim, ax_y):
        counts, edges = np.histogram(chain, bins=100, range=lim)
        x_ = (edges[1:] + edges[:-1]) / 2
        y_ = counts

        if ax is ax_x:
            plotargs = x_, y_
            fillfunc = ax.fill_between
        else:
            x_ = x_[::-1]
            ax.set_xlim(0, 1.5*y_.max())
            plotargs = y_, x_
            fillfunc = ax.fill_betweenx

        ax.plot(*plotargs, lw=1.7, color=plt.cm.Blues(0.8))
        fillfunc(x_, y_, color=plt.cm.Blues(0.1), zorder=-10)

    set_loc(ax_j, nbins=4, minor=2, steps=[1, 2, 3, 4, 5, 10])

    for ax in fig.axes:
        ax.tick_params(which='both', top='off', right='off')
        spines = ['top', 'right']
        if ax is ax_x or ax is ax_y:
            ax.tick_params(labelbottom='off', labelleft='off')
            if ax is ax_x:
                ax.tick_params('x', which='both', top='off')
                ax.tick_params('y', which='both', left='off', right='off')
                spines += ['left']
            else:
                ax.tick_params('x', which='both', top='off', bottom='off')
                ax.tick_params('y', which='both', right='off')
                spines += ['bottom']
        for spine in spines:
            ax.spines[spine].set_visible(False)

    ax_j.set_xlim(xlim)
    ax_j.set_ylim(ylim)

    ax_j.set_xlabel(xlabel, labelpad=10)
    ax_j.set_ylabel(ylabel, labelpad=10)

    gs.tight_layout(fig=fig, pad=.1)


def _observables_plot(model_data, exp_data, posterior=False, vertical=True):
    id_parts = [
        ('pion',   r'$\pi^\pm$', 'Blues'),
        ('kaon',   r'$K^\pm$', 'Greens'),
        ('proton', r'$p\bar p$', 'Reds')
    ]

    flows = [(str(n), '$v_{}$'.format(n), c)
             for n, c in enumerate(['GnBu', 'Purples', 'Oranges'], start=2)]

    plots = [
        ('dN_dy', 'Identified particle yields', r'$dN/dy$', (1, 4e3),
         id_parts),
        ('mean_pT', 'Identified particle mean $p_T$',
         r'$p_T$ [GeV]', (0, 1.8), id_parts),
        ('vn', 'Flow cumulants', r'$v_n\{2\}$', (0, 0.12), flows),
    ]

    if vertical:
        fig, axes = plt.subplots(nrows=len(plots), figsize=(8, 15))
    else:
        fig, axes = plt.subplots(ncols=len(plots), figsize=(22, 6))

    with \
            h5py.File(model_data, 'r') as model, \
            h5py.File(exp_data, 'r') as exp:
        if posterior:
            samples = np.random.randint(0, model['chain'].shape[0], size=100)

        for ax, (obs, title, ylabel, ylim, subplots) in zip(axes, plots):
            for subobs, label, cmap in subplots:
                color = getattr(plt.cm, cmap)(0.6)

                n = 6 if obs == 'vn' and subobs != '2' else 8

                x, y, yerr = (exp[obs][subobs][k][:n]
                              for k in ['x', 'y', 'yerr'])

                ax.errorbar(x, y, yerr=yerr, fmt='o',
                            capsize=0, color='0.2', zorder=1000)

                ax.text(x[-1] + 2, y[-1], label, ha='left', va='center',
                        size=fontnormal)

                kwargs = dict(color=color, alpha=0.2, lw=0.5)

                if posterior:
                    for i in samples:
                        ax.plot(x, model['samples'][obs][subobs][i], **kwargs)
                else:
                    for y in model[obs][subobs]['Y'][:, :n]:
                        ax.plot(x, y, **kwargs)

            ax.set_xlim(0, 70)
            ax.set_ylim(ylim)
            ax.set_ylabel(ylabel, labelpad=10)
            ax.set_title(title)

            if obs == 'dN_dy':
                ax.set_yscale('log')
                ax.minorticks_off()
            else:
                set_loc(ax, 'y', nbins=6)

    if vertical:
        axes[-1].set_xlabel('Centrality %', labelpad=10)
        finish(h_pad=1)
    else:
        for ax in axes:
            ax.set_xlabel('Centrality %', labelpad=10)
        finish(w_pad=0.5)


@plot
def observables_horizontal_prior(batch_obs, exp_data, **kwargs):
    _observables_plot(batch_obs, exp_data, posterior=False, vertical=False)


@plot
def observables_vertical_prior(batch_obs, exp_data, **kwargs):
    _observables_plot(batch_obs, exp_data, posterior=False, vertical=True)


@plot
def observables_horizontal_posterior(calibration, exp_data, **kwargs):
    _observables_plot(calibration, exp_data, posterior=True, vertical=False)


@plot
def observables_vertical_posterior(calibration, exp_data, **kwargs):
    _observables_plot(calibration, exp_data, posterior=True, vertical=True)


def _zetas(T, Tc=0.180,
           A1=-13.77, A2=27.55, A3=13.45,
           lam1=0.9, lam2=0.25, lam3=0.9, lam4=0.22,
           sig1=0.025, sig2=0.13, sig3=0.0025, sig4=0.022):
    t = np.asarray(T)/Tc
    zetas = np.empty_like(t)

    low = t < 0.995
    xm1 = t[low] - 1
    zetas[low] = lam3*np.exp(xm1/sig3) + lam4*np.exp(xm1/sig4) + 0.03

    high = t > 1.05
    xm1 = t[high] - 1
    zetas[high] = lam1*np.exp(-xm1/sig1) + lam2*np.exp(-xm1/sig2) + 0.001

    mid = ~(low | high)
    x = t[mid]
    zetas[mid] = A1*x*x + A2*x - A3

    return zetas


def _viscosity_samples(calibration=None):
    fig, axes = plt.subplots(nrows=2, figsize=(7.85, 9))
    etas_ax, zetas_ax = axes

    Tmin, Tc, Tmax = 0.145, 0.154, 0.300
    T1 = np.linspace(Tmin, Tmax, 1000)
    T2 = np.linspace(Tc, Tmax, 100)

    if calibration is not None:
        line_kwargs = dict(color=plt.cm.Blues(0.7), alpha=0.2, lw=0.7)

        with h5py.File(calibration, 'r') as cal:
            sample_idx = np.random.randint(0, cal['chain'].shape[0], size=200)

            for i in sample_idx:
                etas_min, etas_slope, zetas_norm = cal['chain'][i, 5:8]
                etas_ax.plot(T2, etas_min + etas_slope*(T2 - Tc),
                             **line_kwargs)
                zetas_ax.plot(T1, zetas_norm*_zetas(T1),
                              **line_kwargs)

    text_kwargs = dict(fontsize=20)
    fill_kwargs = dict(color='0.9', zorder=-1000)

    etas_ax.fill_between(T2, 0.3 + 2*(T2 - Tc), **fill_kwargs)
    etas_ax.axvline(Tc, ls='dashed', lw=1, color='0.3')
    etas_ax.text(Tc + 0.003, 0.5, '$T_c = \,{}$ GeV'.format(Tc),
                 ha='left', va='center', **text_kwargs)

    points = etas_ax.transData.transform([
        (Tc, 0.3),
        (Tmax, 0.3 + 2*(Tmax-Tc))
    ])
    dx, dy = points[1] - points[0]
    angle = 180/np.pi * np.arctan2(dy, dx)
    etas_ax.text((Tmax + Tc)/2, 0.28 + Tmax - Tc, 'initial range',
                 rotation=angle, ha='center', **text_kwargs)

    etas_ax.text(
        0.205, 0.03,
        '$(\eta/s)(T) =\,'
        '(\eta/s)_\mathrm{min} + (\eta/s)_\mathrm{slope}(T - T_c)$',
        **text_kwargs
    )
    etas_ax.set_ylabel(r'$\eta/s$', labelpad=10)

    zetas_ax.plot(T1, _zetas(T1), color=offblack, lw=2)
    zetas_ax.fill_between(T1, 2*_zetas(T1), **fill_kwargs)
    zetas_ax.text(0.193, 0.52, 'initial range', **text_kwargs)
    zetas_ax.text(
        0.22, 0.40,
        '$(\zeta/s)(T)$ from Denicol et. al.\n'
        'vary overall normalization\n'
        'black line: norm = 1',
        va='top', **text_kwargs
    )
    zetas_ax.set_xlabel('Temperature [GeV]', labelpad=10)
    zetas_ax.set_ylabel(r'$\zeta/s$', labelpad=10)

    for ax in axes:
        ax.set_xticks(np.arange(150, 301, 50)/1000)
        ax.set_xlim(Tmin, Tmax)

    finish(h_pad=1)


@plot
def viscosity_samples(calibration, **kwargs):
    _viscosity_samples(calibration)


@plot
def viscosity_samples_empty(**kwargs):
    _viscosity_samples()


@plot
def mode_observables(batch_obs_mode, exp_data, **kwargs):
    id_parts = [
        ('pion',   r'$\pi^\pm$', 'Blues'),
        ('kaon',   r'$K^\pm$', 'Greens'),
        ('proton', r'$p\bar p$', 'Reds')
    ]

    flows = [(str(n), '$v_{}$'.format(n), c)
             for n, c in enumerate(['GnBu', 'Purples', 'Oranges'], start=2)]

    plots = [
        ('dN_dy', 'Identified particle yields', r'$dN/dy$', (1, 3e3),
         id_parts),
        ('mean_pT', 'Identified particle mean $p_T$',
         r'$p_T$ [GeV]', (0, 1.5), id_parts),
        ('vn', 'Flow cumulants', r'$v_n\{2\}$', (0, 0.11), flows),
    ]

    fig = plt.figure(figsize=(25, 9))
    gs = plt.GridSpec(3, len(plots))

    with \
            h5py.File(batch_obs_mode, 'r') as mode, \
            h5py.File(exp_data, 'r') as exp:
        for n, (obs, title, ylabel, ylim, subplots) in enumerate(plots):
            ax = fig.add_subplot(gs[:2, n])
            ratio_ax = fig.add_subplot(gs[2, n])

            for subobs, label, cmap in subplots:
                color = getattr(plt.cm, cmap)(0.7)
                ncent = min(i[obs][subobs]['x'].size for i in [mode, exp])

                x = mode[obs][subobs]['x'][:ncent]
                y = mode[obs][subobs]['Y'][0, :ncent]
                ax.plot(x, y, color=color, lw=1.7)

                yexp, yexperr = (exp[obs][subobs][k][:ncent]
                                 for k in ['y', 'yerr'])
                ax.errorbar(x, yexp, yerr=yexperr, fmt='o',
                            capsize=0, color='0.2', zorder=1000)

                ax.text(x[-1] + 3, y[-1], label, ha='left', va='center',
                        size=fontnormal)

                ratio_ax.plot(x, y/yexp, color=color, lw=2)

            ax.set_ylim(ylim)
            ax.set_ylabel(ylabel, labelpad=10)
            ax.set_title(title)

            if obs == 'dN_dy':
                ax.set_yscale('log')
                ax.minorticks_off()
            else:
                set_loc(ax, 'y', nbins=6)

            ratio_ax.axhline(1, color='0.5', lw=1, zorder=-100)
            ratio_ax.axhspan(0.9, 1.1, color='0.95', zorder=-200)

            ratio_ax.set_xlabel('Centrality %', labelpad=10)
            ratio_ax.set_ylim(0.8, 1.2)
            ratio_ax.set_yticks(np.arange(80, 121, 10)/100)
            ratio_ax.set_ylabel('Ratio', labelpad=10)

    finish(pad=0.2, h_pad=0.5, w_pad=1.5)


@plot
def design(design, **kwargs):
    fig = plt.figure(figsize=(7, 7))
    ratio = 5
    gs = plt.GridSpec(ratio + 1, ratio + 1)

    ax_j = fig.add_subplot(gs[1:, :-1])
    ax_x = fig.add_subplot(gs[0, :-1], sharex=ax_j)
    ax_y = fig.add_subplot(gs[1:, -1], sharey=ax_j)

    with h5py.File(design, 'r') as f:
        i, j = 5, 6
        x = f['design/main'][:, i]
        y = f['design/main'][:, j]
        xlabel = f['labels'][i]
        ylabel = f['labels'][j]
        xlim = f['range'][i, :]
        ylim = f['range'][j, :]

    ax_j.plot(x, y, 'o', ms=6, color=plt.cm.Blues(0.75), mec='white', mew=.5)

    hist_kw = dict(bins=30, color=plt.cm.Blues(0.4), edgecolor='white')
    ax_x.hist(x, **hist_kw)
    ax_y.hist(y, orientation='horizontal', **hist_kw)

    for ax in fig.axes:
        ax.tick_params(top='off', right='off')
        spines = ['top', 'right']
        if ax is ax_x:
            spines += ['left']
        elif ax is ax_y:
            spines += ['bottom']
        for spine in spines:
            ax.spines[spine].set_visible(False)
        for ax_name in 'xaxis', 'yaxis':
            getattr(ax, ax_name).set_ticks_position('none')

    for ax in ax_x, ax_y:
        ax.tick_params(labelbottom='off', labelleft='off')

    ax_j.set_xlim(xlim)
    ax_j.set_ylim(ylim)
    set_loc(ax_j, nbins=4, steps=[1, 2, 3, 4, 5, 10])

    ax_j.set_xlabel(xlabel, labelpad=10)
    ax_j.set_ylabel(ylabel, labelpad=10)

    gs.tight_layout(fig=fig, pad=0.)


@plot
def pca(batch_obs, **kwargs):
    fig = plt.figure(figsize=(7, 7))
    ratio = 5
    gs = plt.GridSpec(ratio + 1, ratio + 1)

    ax_j = fig.add_subplot(gs[1:, :-1])
    ax_x = fig.add_subplot(gs[0, :-1], sharex=ax_j)
    ax_y = fig.add_subplot(gs[1:, -1], sharey=ax_j)

    with h5py.File(batch_obs, 'r') as f:
        i = 3
        x = f['dN_dy/pion/Y'][:, i]
        y = f['vn/2/Y'][:, i]
        xlabel = r'$dN_{\pi^\pm}/dy$'
        ylabel = r'$v_2\{2\}$'
        xlim = 0, 2000
        ylim = 0, 0.12

    ax_j.plot(x, y, 'o', ms=6, color=plt.cm.Blues(0.75), mec='white', mew=.5,
              zorder=10)

    hist_kw = dict(bins=16, color=plt.cm.Blues(0.4), edgecolor='white')
    ax_x.hist(x, **hist_kw)
    ax_y.hist(y, orientation='horizontal', **hist_kw)

    xy = np.column_stack((x, y))
    xymean = xy.mean(axis=0)
    xystd = xy.std(axis=0)
    xy -= xymean
    xy /= xystd
    pca = mtd.PCA(xy)
    pc = 5.5 * xystd * pca.weights[:, np.newaxis] * pca.pc

    for w, p in zip(pca.weights, pc):
        if np.all(p < 0):
            p *= -1
        ax_j.annotate('', xymean + p, xymean,
                      zorder=20, arrowprops=dict(
                          arrowstyle='->', shrinkA=0, shrinkB=0,
                          color=offblack, lw=1.5
                      ))
        ax_j.text(*(xymean + p + (.8, .002)*np.sign(p)),
                  s='{:.0f}%'.format(100*w), color=offblack, fontsize=20,
                  ha='center', va='top' if p[1] < 0 else 'bottom',
                  zorder=20)

    for ax in fig.axes:
        ax.tick_params(top='off', right='off')
        spines = ['top', 'right']
        if ax is ax_x:
            spines += ['left']
        elif ax is ax_y:
            spines += ['bottom']
        for spine in spines:
            ax.spines[spine].set_visible(False)
        for ax_name in 'xaxis', 'yaxis':
            getattr(ax, ax_name).set_ticks_position('none')

    for ax in ax_x, ax_y:
        ax.tick_params(labelbottom='off', labelleft='off')

    ax_j.set_xlim(xlim)
    ax_j.set_ylim(ylim)
    set_loc(ax_j, nbins=4, steps=[1, 2, 3, 4, 5, 10])

    ax_j.set_xlabel(xlabel, labelpad=10)
    ax_j.set_ylabel(ylabel, labelpad=10)

    ax_j.annotate('20–30%', (.03, .03), xycoords='axes fraction',
                  ha='left', va='bottom', fontsize=20)

    gs.tight_layout(fig=fig, pad=0.)


@plot
def validation(calibration, batch_obs_validation, **kwargs):
    observables = [
        ('dN_dy/pion', r'$dN_{\pi^\pm}/dy$', (0, 3200)),
        ('mean_pT/pion', r'$\langle p_T \rangle_{\pi^\pm}$', (0.4, 0.75)),
        ('vn/2', r'$v_2\{2\}$', (0, 0.13)),
    ]

    cent_edges = [0, 5, 10, 20, 30, 40, 50, 60, 70, 80]
    cent_bins = list(zip(cent_edges[:-1], cent_edges[1:]))

    fig, axes = plt.subplots(ncols=len(observables), figsize=(20, 7))

    with \
            h5py.File(calibration, 'r') as cal, \
            h5py.File(batch_obs_validation, 'r') as vld:
        for (key, label, lim), ax in zip(observables, axes):
            for i, cmap in (0, 'Blues'), (4, 'Oranges'):
                x = cal['validation'][key]['Y'][:, i]
                xerr = cal['validation'][key]['Yerr'][:, i]
                y = vld[key]['Y'][:, i]
                yerr = vld[key]['Yerr'][:, i]
                ax.errorbar(
                    x, y, xerr=xerr, yerr=yerr, fmt='o', ms=7, capsize=0,
                    color=getattr(plt.cm, cmap)(0.8), mec='white', mew=0.5,
                    label='–'.join(map(str, cent_bins[i])) + '%'
                )
            ax.plot(lim, lim, lw=1, color='.7', zorder=-10)
            ax.set_xlim(lim)
            ax.set_ylim(lim)
            ax.set_aspect('equal')
            ax.set_xlabel('Predicted ' + label, labelpad=10)
            if ax.is_first_col():
                ax.set_ylabel('Observed', labelpad=10)
                ax.legend(loc='best', handletextpad=0)
            set_loc(ax)

    finish(pad=0.7)


def main():
    parser = argparse.ArgumentParser()

    parser.add_argument('--design', default='../data/model/design.hdf')
    parser.add_argument('--calibration', default='../calibration/results.hdf')
    parser.add_argument('--exp-data', default='../data/exp/data.hdf')

    for suffix in ['', '-mode', '-validation']:
        parser.add_argument(
            '--batch-obs' + suffix,
            default='../data/model/batch-observables{}.hdf'.format(suffix)
        )

    parser.add_argument('plots', nargs='*')

    args = parser.parse_args()

    if args.plots:
        for i in args.plots:
            if i.endswith('.pdf'):
                i = i[:-4]
            if i in plot_functions:
                plot_functions[i](**vars(args))
            else:
                print('unknown plot:', i)
    else:
        for f in plot_functions.values():
            f(**vars(args))


if __name__ == "__main__":
    main()
